name: Mi primer pipeline

on:
    push:
        branches: [main]

jobs:
    prueba:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar codigo
              uses: actions/checkout@v4

            - name: Mostrar mensaje
              run: echo "Pipeline funcionando correctamente"
              
            - name: Verificar archivos
              run: echo "Verificando la existencia de los archivos..."
               test -f index.html
               test -f style.css
               test -f script.js
               echo "Todos los archivos existen"

